package org.hni.user.om;

// Generated Apr 19, 2017 11:39:46 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hni.common.om.Persistable;

/**
 * VolunteerAvailability generated by hbm2java
 */
@Entity
@Table(name = "volunteer_availability")
public class VolunteerAvailability implements Persistable,java.io.Serializable {

	private Integer id;
	private Date created;
	private int createdBy;
	private int volunteerId;
	private int timeline;
	private String weekday;

	public VolunteerAvailability() {
	}

	public VolunteerAvailability(Date created, int createdBy, int volunteerId,
			int timeline, String weekday) {
		this.created = created;
		this.createdBy = createdBy;
		this.volunteerId = volunteerId;
		this.timeline = timeline;
		this.weekday = weekday;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "volunteer_id", nullable = false)
	public int getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	@Column(name = "timeline", nullable = false)
	public int getTimeline() {
		return this.timeline;
	}

	public void setTimeline(int timeline) {
		this.timeline = timeline;
	}

	@Column(name = "weekday", nullable = false, length = 50)
	public String getWeekday() {
		return this.weekday;
	}

	public void setWeekday(String weekday) {
		this.weekday = weekday;
	}

}
